/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AttorneyAnalyticsApiApi,
  AuthenticationApiApi,
  CallbackApiApi,
  CaseAnalyticsApiApi,
  CaseDocketApiApi,
  CaseDocumentsApiApi,
  CaseExportApiApi,
  CaseSearchApiApi,
  CaseTrackingApiApi,
  CaseUpdateApiApi,
  CourtAvailabilityApiApi,
  CourtStandardsApiApi,
  JudgeAnalyticsApiApi,
  LawFirmAnalyticsApiApi,
  PacerApiApi,
  PacerCredentialApiApi,
  PartyAnalyticsApiApi,
  UsageApiApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { UniCourtCustom } from "./client-custom";

export class UniCourt extends UniCourtCustom {
  readonly attorneyAnalyticsApi: AttorneyAnalyticsApiApi;
  readonly authenticationApi: AuthenticationApiApi;
  readonly callbackApi: CallbackApiApi;
  readonly caseAnalyticsApi: CaseAnalyticsApiApi;
  readonly caseDocketApi: CaseDocketApiApi;
  readonly caseDocumentsApi: CaseDocumentsApiApi;
  readonly caseExportApi: CaseExportApiApi;
  readonly caseSearchApi: CaseSearchApiApi;
  readonly caseTrackingApi: CaseTrackingApiApi;
  readonly caseUpdateApi: CaseUpdateApiApi;
  readonly courtAvailabilityApi: CourtAvailabilityApiApi;
  readonly courtStandardsApi: CourtStandardsApiApi;
  readonly judgeAnalyticsApi: JudgeAnalyticsApiApi;
  readonly lawFirmAnalyticsApi: LawFirmAnalyticsApiApi;
  readonly pacerApi: PacerApiApi;
  readonly pacerCredentialApi: PacerCredentialApiApi;
  readonly partyAnalyticsApi: PartyAnalyticsApiApi;
  readonly usageApi: UsageApiApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.attorneyAnalyticsApi = new AttorneyAnalyticsApiApi(configuration);
    this.authenticationApi = new AuthenticationApiApi(configuration);
    this.callbackApi = new CallbackApiApi(configuration);
    this.caseAnalyticsApi = new CaseAnalyticsApiApi(configuration);
    this.caseDocketApi = new CaseDocketApiApi(configuration);
    this.caseDocumentsApi = new CaseDocumentsApiApi(configuration);
    this.caseExportApi = new CaseExportApiApi(configuration);
    this.caseSearchApi = new CaseSearchApiApi(configuration);
    this.caseTrackingApi = new CaseTrackingApiApi(configuration);
    this.caseUpdateApi = new CaseUpdateApiApi(configuration);
    this.courtAvailabilityApi = new CourtAvailabilityApiApi(configuration);
    this.courtStandardsApi = new CourtStandardsApiApi(configuration);
    this.judgeAnalyticsApi = new JudgeAnalyticsApiApi(configuration);
    this.lawFirmAnalyticsApi = new LawFirmAnalyticsApiApi(configuration);
    this.pacerApi = new PacerApiApi(configuration);
    this.pacerCredentialApi = new PacerCredentialApiApi(configuration);
    this.partyAnalyticsApi = new PartyAnalyticsApiApi(configuration);
    this.usageApi = new UsageApiApi(configuration);
  }

}
