/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccessTokenIdResponse } from './access-token-id-response';

/**
 * 
 * @export
 * @interface AccessTokenIdListResponse
 */
export interface AccessTokenIdListResponse {
    /**
     * Array of access tokens Id.
     * @type {Array<AccessTokenIdResponse>}
     * @memberof AccessTokenIdListResponse
     */
    'AccessTokenIdArray': Array<AccessTokenIdResponse>;
    /**
     * Name of the object.
     * @type {string}
     * @memberof AccessTokenIdListResponse
     */
    'object': string;
}

