/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssociatedNormAttorney } from './associated-norm-attorney';

/**
 * 
 * @export
 * @interface AssociatedNormAttorneyResponse
 */
export interface AssociatedNormAttorneyResponse {
    /**
     * 
     * @type {Array<AssociatedNormAttorney>}
     * @memberof AssociatedNormAttorneyResponse
     */
    'associatedNormAttorneyArray': Array<AssociatedNormAttorney>;
    /**
     * Next page of results if applicable.
     * @type {string}
     * @memberof AssociatedNormAttorneyResponse
     */
    'nextPageAPI': string | null;
    /**
     * Previous page of results if applicable.
     * @type {string}
     * @memberof AssociatedNormAttorneyResponse
     */
    'previousPageAPI': string | null;
    /**
     * Total no. of results for this criteria.
     * @type {number}
     * @memberof AssociatedNormAttorneyResponse
     */
    'totalCount': number;
    /**
     * Total no. of pages.
     * @type {number}
     * @memberof AssociatedNormAttorneyResponse
     */
    'totalPages': number;
}

