/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseTimeline } from './case-timeline';

/**
 * Associated Judge
 * @export
 * @interface AssociatedNormJudge
 */
export interface AssociatedNormJudge {
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormJudge
     */
    'version': string;
    /**
     * 
     * @type {number}
     * @memberof AssociatedNormJudge
     */
    'caseCount': number;
    /**
     * Link to related cases for this association.
     * @type {string}
     * @memberof AssociatedNormJudge
     */
    'caseSearchAPI': string;
    /**
     * 
     * @type {CaseTimeline}
     * @memberof AssociatedNormJudge
     */
    'caseTimeline': CaseTimeline;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormJudge
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormJudge
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormJudge
     */
    'middleName': string | null;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormJudge
     */
    'name': string;
    /**
     * Link to Details from the Judge.
     * @type {string}
     * @memberof AssociatedNormJudge
     */
    'normJudgeAPI': string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormJudge
     */
    'normJudgeId': string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormJudge
     */
    'object': string;
}

