/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Contact } from './contact';

/**
 * 
 * @export
 * @interface AssociatedSoSPerson
 */
export interface AssociatedSoSPerson {
    /**
     * 
     * @type {Contact}
     * @memberof AssociatedSoSPerson
     */
    'contact': Contact;
    /**
     * 
     * @type {string}
     * @memberof AssociatedSoSPerson
     */
    'entityName': string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedSoSPerson
     */
    'entityType': AssociatedSoSPersonEntityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AssociatedSoSPerson
     */
    'object': string;
}

type AssociatedSoSPersonEntityTypeEnum = 'Partner' | 'Agent' | 'CEO' | 'Partner/General Member' | 'Partner/GeneralMember'


