/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BarRecordPreview } from './bar-record-preview';
import { CaseTimeline } from './case-timeline';

/**
 * 
 * @export
 * @interface AssociatedNormAttorney
 */
export interface AssociatedNormAttorney {
    /**
     * 
     * @type {number}
     * @memberof AssociatedNormAttorney
     */
    'caseCount': number;
    /**
     * Link to related cases for this association.
     * @type {string}
     * @memberof AssociatedNormAttorney
     */
    'caseSearchAPI': string;
    /**
     * 
     * @type {CaseTimeline}
     * @memberof AssociatedNormAttorney
     */
    'caseTimeline': CaseTimeline;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormAttorney
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormAttorney
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormAttorney
     */
    'middleName': string | null;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormAttorney
     */
    'name': string;
    /**
     * Link to details for the Attorney.
     * @type {string}
     * @memberof AssociatedNormAttorney
     */
    'normAttorneyAPI': string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormAttorney
     */
    'normAttorneyId': string;
    /**
     * 
     * @type {string}
     * @memberof AssociatedNormAttorney
     */
    'object': string;
    /**
     * 
     * @type {Array<BarRecordPreview>}
     * @memberof AssociatedNormAttorney
     */
    'stateBarDataArray': Array<BarRecordPreview>;
}

