/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Name of the attorney\'s law firm as provided by Court. This can be null as some Courts do not provide this as a separate field.
 * @export
 * @interface AttorneyLawFirm
 */
export interface AttorneyLawFirm {
    /**
     * ID for the law firm of an attorney in this case. This ID is unique within a case and NOT across cases. If the same attorney were to appear in another case this ID would be different.
     * @type {string}
     * @memberof AttorneyLawFirm
     */
    'attorneyLawFirmId': string | null;
    /**
     * Is the date when the document was first fetched from the court site.
     * @type {string}
     * @memberof AttorneyLawFirm
     */
    'firstFetchDate': string;
    /**
     * Signifies if the attorney as this attorney type is currently isVisible or not for the case.
     * @type {boolean}
     * @memberof AttorneyLawFirm
     */
    'isVisible': boolean;
    /**
     * Is the date when the document was last fetched from the court site.
     * @type {string}
     * @memberof AttorneyLawFirm
     */
    'lastFetchDate': string;
    /**
     * Name of the law firm as provided by Court.
     * @type {string}
     * @memberof AttorneyLawFirm
     */
    'name': string;
    /**
     * Name of the object
     * @type {string}
     * @memberof AttorneyLawFirm
     */
    'object': string;
}

