/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BarSourceDataAdministrativeActionsArrayInner
 */
export interface BarSourceDataAdministrativeActionsArrayInner {
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataAdministrativeActionsArrayInner
     */
    'description': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataAdministrativeActionsArrayInner
     */
    'caseNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataAdministrativeActionsArrayInner
     */
    'effectiveDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataAdministrativeActionsArrayInner
     */
    'resultingStatus': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataAdministrativeActionsArrayInner
     */
    'type': string | null;
}

