/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BarSourceDataFeesOptionsArrayInner
 */
export interface BarSourceDataFeesOptionsArrayInner {
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataFeesOptionsArrayInner
     */
    'contingencyFees': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataFeesOptionsArrayInner
     */
    'flatFees': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataFeesOptionsArrayInner
     */
    'hourlyRate': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataFeesOptionsArrayInner
     */
    'paymentPlans': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataFeesOptionsArrayInner
     */
    'slidingScaleFees': string | null;
}

