/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BarSourceDataPublicHearingArrayInner
 */
export interface BarSourceDataPublicHearingArrayInner {
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataPublicHearingArrayInner
     */
    'conduct': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataPublicHearingArrayInner
     */
    'date': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataPublicHearingArrayInner
     */
    'issuedBy': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataPublicHearingArrayInner
     */
    'order': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataPublicHearingArrayInner
     */
    'respondent': string | null;
}

