/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BarSourceDataName
 */
export interface BarSourceDataName {
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataName
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataName
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataName
     */
    'middleName': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataName
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataName
     */
    'prefix': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataName
     */
    'suffix': string | null;
}

