/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BarSourceDataOtherJurisdictionArrayInner
 */
export interface BarSourceDataOtherJurisdictionArrayInner {
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataOtherJurisdictionArrayInner
     */
    'barNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataOtherJurisdictionArrayInner
     */
    'state': string | null;
}

