/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BarSourceDataEmploymentHistoryArrayInner
 */
export interface BarSourceDataEmploymentHistoryArrayInner {
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataEmploymentHistoryArrayInner
     */
    'employer': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataEmploymentHistoryArrayInner
     */
    'endDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataEmploymentHistoryArrayInner
     */
    'startDate': string | null;
}

