/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BarSourceDataTenYearDisciplineArrayInner
 */
export interface BarSourceDataTenYearDisciplineArrayInner {
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataTenYearDisciplineArrayInner
     */
    'description': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataTenYearDisciplineArrayInner
     */
    'actionDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataTenYearDisciplineArrayInner
     */
    'reference': string | null;
}

