/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BarSourceDataDisciplinaryHistoryArrayInner
 */
export interface BarSourceDataDisciplinaryHistoryArrayInner {
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'action': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'caseNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'complaint': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'contactId': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'dateOfAction': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'definition': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'disciplinaryDecision': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'entryDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'information': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'link': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'note': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'probationDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'reinstatedDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'rule': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'ruleNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'sectionDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'status': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'stayDate': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'supremeCourt': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'term': string | null;
    /**
     * 
     * @type {string}
     * @memberof BarSourceDataDisciplinaryHistoryArrayInner
     */
    'typeOfAction': string | null;
}

