/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * StartDate and endDate of the billing cycle.
 * @export
 * @interface BillingCycleUsageResponseBillingCycle
 */
export interface BillingCycleUsageResponseBillingCycle {
    /**
     * End date of the billing cycle.
     * @type {string}
     * @memberof BillingCycleUsageResponseBillingCycle
     */
    'endDate': string;
    /**
     * Start date of the billing cycle.
     * @type {string}
     * @memberof BillingCycleUsageResponseBillingCycle
     */
    'startDate': string;
}

