/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Total number of callbackFailures including caseUpdate, caseDocumentOrder and caseExport for the billing cycle.
 * @export
 * @interface BillingCycleUsageResponseApiCallsCredited
 */
export interface BillingCycleUsageResponseApiCallsCredited {
    /**
     * Total API calls credited back for the billing cycle
     * @type {number}
     * @memberof BillingCycleUsageResponseApiCallsCredited
     */
    'count': number;
    /**
     * Last Updated date and time for the field apiCallsCredited
     * @type {string}
     * @memberof BillingCycleUsageResponseApiCallsCredited
     */
    'lastUpdated': string | null;
}

