/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseUpdatePreview } from './case-update-preview';

/**
 * 
 * @export
 * @interface CaseUpdateListResponse
 */
export interface CaseUpdateListResponse {
    /**
     * Array of case update objects.
     * @type {Array<CaseUpdatePreview>}
     * @memberof CaseUpdateListResponse
     */
    'caseUpdatePreviewArray': Array<CaseUpdatePreview>;
    /**
     * Link for the next page.
     * @type {string}
     * @memberof CaseUpdateListResponse
     */
    'nextPageAPI': string | null;
    /**
     * Name of the object.
     * @type {string}
     * @memberof CaseUpdateListResponse
     */
    'object': string;
    /**
     * Current page number.
     * @type {number}
     * @memberof CaseUpdateListResponse
     */
    'pageNumber': number;
    /**
     * Link for the previous page.
     * @type {string}
     * @memberof CaseUpdateListResponse
     */
    'previousPageAPI': string | null;
    /**
     * Total number of case update objects available.
     * @type {number}
     * @memberof CaseUpdateListResponse
     */
    'totalCount': number;
    /**
     * Total number of pages available.
     * @type {number}
     * @memberof CaseUpdateListResponse
     */
    'totalPages': number;
}

