/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Charge } from './charge';
import { ChargeAdditionalData } from './charge-additional-data';
import { ChargeDegree } from './charge-degree';
import { ChargeSeverity } from './charge-severity';

/**
 * 
 * @export
 * @interface CaseCharge
 */
export interface CaseCharge {
    /**
     * 
     * @type {Charge}
     * @memberof CaseCharge
     */
    'charge': Charge | null;
    /**
     * 
     * @type {Array<ChargeAdditionalData>}
     * @memberof CaseCharge
     */
    'chargeAdditionalDataArray': Array<ChargeAdditionalData>;
    /**
     * 
     * @type {ChargeDegree}
     * @memberof CaseCharge
     */
    'chargeDegree': ChargeDegree | null;
    /**
     * 
     * @type {ChargeSeverity}
     * @memberof CaseCharge
     */
    'chargeSeverity': ChargeSeverity | null;
    /**
     * Name of the object
     * @type {string}
     * @memberof CaseCharge
     */
    'object': string;
}

