/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CaseTimeline
 */
export interface CaseTimeline {
    /**
     * The first date when the two entities have appeared together in the case. (These dates are determined from case filed dates)
     * @type {string}
     * @memberof CaseTimeline
     */
    'firstCaseFiledDate': string;
    /**
     * The last date when the two entities have appeared together in the case. (These dates are determined from case filed dates)
     * @type {string}
     * @memberof CaseTimeline
     */
    'lastCaseFiledDate': string;
    /**
     * 
     * @type {string}
     * @memberof CaseTimeline
     */
    'object': string;
}

