/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseCountAnalyticsByCourtType } from './case-count-analytics-by-court-type';

/**
 * Case Counts by Court Type.
 * @export
 * @interface CaseCountAnalyticsByCourtTypeResponse
 */
export interface CaseCountAnalyticsByCourtTypeResponse {
    /**
     * Next page of results if applicable.
     * @type {string}
     * @memberof CaseCountAnalyticsByCourtTypeResponse
     */
    'nextPageAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByCourtTypeResponse
     */
    'object': string;
    /**
     * Link to previous page of results.
     * @type {string}
     * @memberof CaseCountAnalyticsByCourtTypeResponse
     */
    'previousPageAPI': string | null;
    /**
     * 
     * @type {Array<CaseCountAnalyticsByCourtType>}
     * @memberof CaseCountAnalyticsByCourtTypeResponse
     */
    'results': Array<CaseCountAnalyticsByCourtType>;
    /**
     * Total no. of Cases for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByCourtTypeResponse
     */
    'totalCaseCount': number;
    /**
     * Total no. of Court Type for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByCourtTypeResponse
     */
    'totalCourtTypeCount': number;
    /**
     * Total no. of pages.
     * @type {number}
     * @memberof CaseCountAnalyticsByCourtTypeResponse
     */
    'totalPages': number;
}

