/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Case } from './case';
import { CaseUpdatePacerOptionsResponse } from './case-update-pacer-options-response';
import { Exception } from './exception';

/**
 * 
 * @export
 * @interface CaseUpdate
 */
export interface CaseUpdate {
    /**
     * 
     * @type {Case}
     * @memberof CaseUpdate
     */
    'case': Case | null;
    /**
     * 
     * @type {string}
     * @memberof CaseUpdate
     */
    'caseAPI': string;
    /**
     * Unique Id for a Case in UniCourt.
     * @type {string}
     * @memberof CaseUpdate
     */
    'caseId': string;
    /**
     * 
     * @type {Exception}
     * @memberof CaseUpdate
     */
    'exception': Exception | null;
    /**
     * Name of the object.
     * @type {string}
     * @memberof CaseUpdate
     */
    'object': string;
    /**
     * 
     * @type {CaseUpdatePacerOptionsResponse}
     * @memberof CaseUpdate
     */
    'pacerOptions': CaseUpdatePacerOptionsResponse | null;
    /**
     * The date and time when the case was last requested for update 
     * @type {string}
     * @memberof CaseUpdate
     */
    'requestedDate': string;
    /**
     * Status of the request.
     * @type {string}
     * @memberof CaseUpdate
     */
    'status': CaseUpdateStatusEnum;
}

type CaseUpdateStatusEnum = 'COMPLETE' | 'FAILURE' | 'IN_PROGRESS'


