/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseCountAnalyticsByCaseFiledDate } from './case-count-analytics-by-case-filed-date';

/**
 * Response for Case Count by filing date.
 * @export
 * @interface CaseCountAnalyticsByCaseFiledDateResponse
 */
export interface CaseCountAnalyticsByCaseFiledDateResponse {
    /**
     * Next page of results if applicable.
     * @type {string}
     * @memberof CaseCountAnalyticsByCaseFiledDateResponse
     */
    'nextPageAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByCaseFiledDateResponse
     */
    'object': string;
    /**
     * Link to previous page of results.
     * @type {string}
     * @memberof CaseCountAnalyticsByCaseFiledDateResponse
     */
    'previousPageAPI': string | null;
    /**
     * 
     * @type {Array<CaseCountAnalyticsByCaseFiledDate>}
     * @memberof CaseCountAnalyticsByCaseFiledDateResponse
     */
    'results': Array<CaseCountAnalyticsByCaseFiledDate>;
    /**
     * Total no. of Cases for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByCaseFiledDateResponse
     */
    'totalCaseCount': number;
    /**
     * Total no. of Case File Date for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByCaseFiledDateResponse
     */
    'totalCaseFiledDateCount': number;
    /**
     * Total no. of pages.
     * @type {number}
     * @memberof CaseCountAnalyticsByCaseFiledDateResponse
     */
    'totalPages': number;
}

