/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CaseTrackSchedule
 */
export interface CaseTrackSchedule {
    /**
     * [] -> if schedule type is daily <br> 1-7 -> if schedule type is weekly <br> 1-31 -> if schedule type is monthly 
     * @type {Array<number>}
     * @memberof CaseTrackSchedule
     */
    'days': Array<number>;
    /**
     * 
     * @type {string}
     * @memberof CaseTrackSchedule
     */
    'type': CaseTrackScheduleTypeEnum;
}

type CaseTrackScheduleTypeEnum = 'daily' | 'weekly' | 'monthly'


