/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseTrackPreview } from './case-track-preview';

/**
 * 
 * @export
 * @interface CaseTrackListResponse
 */
export interface CaseTrackListResponse {
    /**
     * Array of cases tracked.
     * @type {Array<CaseTrackPreview>}
     * @memberof CaseTrackListResponse
     */
    'caseTrackPreviewArray': Array<CaseTrackPreview>;
    /**
     * Link for the next page.
     * @type {string}
     * @memberof CaseTrackListResponse
     */
    'nextPageAPI': string | null;
    /**
     * Name of the object.
     * @type {string}
     * @memberof CaseTrackListResponse
     */
    'object': string;
    /**
     * Current page number.
     * @type {number}
     * @memberof CaseTrackListResponse
     */
    'pageNumber': number;
    /**
     * Link for the previous page.
     * @type {string}
     * @memberof CaseTrackListResponse
     */
    'previousPageAPI': string | null;
    /**
     * Total number of case track available.
     * @type {number}
     * @memberof CaseTrackListResponse
     */
    'totalCount': number;
    /**
     * Total number of pages available.
     * @type {number}
     * @memberof CaseTrackListResponse
     */
    'totalPages': number;
}

