/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Provides Court Data per State Jurisdiction for an entity.
 * @export
 * @interface CaseAnalyticsAPI
 */
export interface CaseAnalyticsAPI {
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByAreaOfLawAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByCaseClassAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByCaseTypeAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByCaseTypeGroupAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByCourtAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByCourtLocationAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByCourtSystemAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByCourtTypeAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByJurisdictionGeoAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByPartyRoleAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'caseCountAnalyticsByPartyRoleGroupAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CaseAnalyticsAPI
     */
    'object': string;
    /**
     * 
     * @type {number}
     * @memberof CaseAnalyticsAPI
     */
    'totalCases': number;
}

