/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseUpdatePacerOptions } from './case-update-pacer-options';

/**
 * 
 * @export
 * @interface CaseUpdateRequest
 */
export interface CaseUpdateRequest {
    /**
     * UniCourt\'s Case Id for update.
     * @type {string}
     * @memberof CaseUpdateRequest
     */
    'caseId': string;
    /**
     * 
     * @type {CaseUpdatePacerOptions}
     * @memberof CaseUpdateRequest
     */
    'pacerOptions'?: CaseUpdatePacerOptions;
}

