/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseCountAnalyticsByNormLawFirm } from './case-count-analytics-by-norm-law-firm';

/**
 * 
 * @export
 * @interface CaseCountAnalyticsByNormLawFirmResponse
 */
export interface CaseCountAnalyticsByNormLawFirmResponse {
    /**
     * Next page of results if applicable.
     * @type {string}
     * @memberof CaseCountAnalyticsByNormLawFirmResponse
     */
    'nextPageAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByNormLawFirmResponse
     */
    'object': string;
    /**
     * Link to previous page of results.
     * @type {string}
     * @memberof CaseCountAnalyticsByNormLawFirmResponse
     */
    'previousPageAPI': string | null;
    /**
     * 
     * @type {Array<CaseCountAnalyticsByNormLawFirm>}
     * @memberof CaseCountAnalyticsByNormLawFirmResponse
     */
    'results': Array<CaseCountAnalyticsByNormLawFirm>;
    /**
     * Total no. of Cases for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByNormLawFirmResponse
     */
    'totalCaseCount': number;
    /**
     * Total no. of NormLawFirm for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByNormLawFirmResponse
     */
    'totalNormLawFirmCount': number;
    /**
     * Total no. of pages.
     * @type {number}
     * @memberof CaseCountAnalyticsByNormLawFirmResponse
     */
    'totalPages': number;
}

