/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Attorneys } from './attorneys';
import { CaseCauseOfAction } from './case-cause-of-action';
import { CaseCharge } from './case-charge';
import { CaseDocuments } from './case-documents';
import { CaseStats } from './case-stats';
import { CaseStatus } from './case-status';
import { CaseType } from './case-type';
import { Court } from './court';
import { CourtLocation } from './court-location';
import { DocketEntries } from './docket-entries';
import { Hearings } from './hearings';
import { Judges } from './judges';
import { Parties } from './parties';
import { RelatedCases } from './related-cases';
import { SourceCaseData } from './source-case-data';

/**
 * 
 * @export
 * @interface Case
 */
export interface Case {
    /**
     * 
     * @type {Attorneys}
     * @memberof Case
     */
    'attorneys': Attorneys | null;
    /**
     * 
     * @type {CaseDocuments}
     * @memberof Case
     */
    'caseDocuments': CaseDocuments | null;
    /**
     * Unique identifier of Case.
     * @type {string}
     * @memberof Case
     */
    'caseId': string;
    /**
     * Case name as provided by Court.
     * @type {string}
     * @memberof Case
     */
    'caseName': string | null;
    /**
     * Case number as provided by Court.
     * @type {string}
     * @memberof Case
     */
    'caseNumber': string;
    /**
     * 
     * @type {CaseStats}
     * @memberof Case
     */
    'caseStats': CaseStats;
    /**
     * 
     * @type {CaseStatus}
     * @memberof Case
     */
    'caseStatus': CaseStatus | null;
    /**
     * 
     * @type {CaseType}
     * @memberof Case
     */
    'caseType': CaseType | null;
    /**
     * Array of cause of Actions that are added to this case.
     * @type {Array<CaseCauseOfAction>}
     * @memberof Case
     */
    'causeOfActionArray': Array<CaseCauseOfAction>;
    /**
     * Array of charges that are added to this case.
     * @type {Array<CaseCharge>}
     * @memberof Case
     */
    'chargeArray': Array<CaseCharge>;
    /**
     * 
     * @type {Court}
     * @memberof Case
     */
    'court': Court | null;
    /**
     * 
     * @type {CourtLocation}
     * @memberof Case
     */
    'courtLocation': CourtLocation | null;
    /**
     * API to get the service statuses of the given case.
     * @type {string}
     * @memberof Case
     */
    'courtServiceStatusAPI': string | null;
    /**
     * Court Service Status ID of the requested case where we can use it to get the service status
     * @type {string}
     * @memberof Case
     */
    'courtServiceStatusId': string | null;
    /**
     * 
     * @type {DocketEntries}
     * @memberof Case
     */
    'docketEntries': DocketEntries | null;
    /**
     * When a case is beyond the threshold of entities we provide this link so that the user can request and get all the data of the case with one additional call. This data will be zipped and sent via a webhoook.
     * @type {string}
     * @memberof Case
     */
    'exportAPI': string;
    /**
     * Filing date for the case provided by the Court. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz
     * @type {string}
     * @memberof Case
     */
    'filedDate': string;
    /**
     * The date and time when the case was first fetched from the Court. This date and time is in UTC. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz,.
     * @type {string}
     * @memberof Case
     */
    'firstFetchDate': string;
    /**
     * This field will be set to TRUE if atleast one document has a preview.
     * @type {boolean}
     * @memberof Case
     */
    'hasDocumentsWithPreview': boolean;
    /**
     * This field determines if this case object has only meta information. If the value is true and if the full information is required you would need to call the updateCase API.
     * @type {boolean}
     * @memberof Case
     */
    'hasOnlyMetaInfo': boolean;
    /**
     * 
     * @type {Hearings}
     * @memberof Case
     */
    'hearings': Hearings | null;
    /**
     * 
     * @type {Judges}
     * @memberof Case
     */
    'judges': Judges | null;
    /**
     * The date and time when the case was last fetched from the Court. This date and time is in UTC. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz, Note: It is not necessary that every time the case is fetched from Court we find changes in the case information. It could be that we already have the latest information from the Court and no changes exist.
     * @type {string}
     * @memberof Case
     */
    'lastFetchDate': string;
    /**
     * The date and time when the case was last fetched from the Court where we found changes in the case information. This date and time is in UTC. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz,
     * @type {string}
     * @memberof Case
     */
    'lastFetchDateWithUpdates': string;
    /**
     * Name of the object
     * @type {string}
     * @memberof Case
     */
    'object': string;
    /**
     * The date and time when parties/attorneys were last updated from the Court. Formatted as YYYY-MM-DDTHH:MM:SS+ZZ:zz, Note: This is currently applicable for Federal PACER cases since we have an option to exclude parties and fetch only latest docket entries when updating cases to save PACER fees.
     * @type {string}
     * @memberof Case
     */
    'participantsLastFetchDate': string | null;
    /**
     * 
     * @type {Parties}
     * @memberof Case
     */
    'parties': Parties | null;
    /**
     * 
     * @type {RelatedCases}
     * @memberof Case
     */
    'relatedCases': RelatedCases | null;
    /**
     * 
     * @type {SourceCaseData}
     * @memberof Case
     */
    'sourceCaseData': SourceCaseData;
    /**
     * The status of source data of case. If the value of sourceDataStatus is SOURCE_DEPRECATED then it means that the Case has been migrated from old court site to a new court site and the data being shown in the API response is from a old court site. If the sourceDataStatus is NO_LONGER_AVAILABLE_IN_COURT then it means that a particular case is invalid in the court site.
     * @type {string}
     * @memberof Case
     */
    'sourceDataStatus': CaseSourceDataStatusEnum;
    /**
     * URL to the case page in UniCourt Application.
     * @type {string}
     * @memberof Case
     */
    'url': string | null;
}

type CaseSourceDataStatusEnum = 'NO_LONGER_AVAILABLE_IN_COURT' | 'SOURCE_DEPRECATED' | 'null'


