/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PreviewDocument } from './preview-document';

/**
 * 
 * @export
 * @interface CaseDocument
 */
export interface CaseDocument {
    /**
     * Description of the document.
     * @type {string}
     * @memberof CaseDocument
     */
    'description': string | null;
    /**
     * Date and time when the document was downloaded and added to the UniCourt Crowd Source Library.
     * @type {string}
     * @memberof CaseDocument
     */
    'addedToLibraryDate': string | null;
    /**
     * UniCourt\'s Case Document ID.
     * @type {string}
     * @memberof CaseDocument
     */
    'caseDocumentId': string;
    /**
     * List of child document ID\'s if exists or else it will be an empty lsit.
     * @type {Array<string>}
     * @memberof CaseDocument
     */
    'childDocumentIdArray': Array<string>;
    /**
     * Document Date when it was filed. The document date will be either explicitly provided byt the court or if the document is associatated to a docket entry then the document date will be of docket entry date.
     * @type {string}
     * @memberof CaseDocument
     */
    'documentFiledDate': string | null;
    /**
     * Link to either view the document if it is downloaded and already present in the UniCourt CrowdSourced Library.
     * @type {string}
     * @memberof CaseDocument
     */
    'downloadAPI': string | null;
    /**
     * Estimated duration of a Order.
     * @type {string}
     * @memberof CaseDocument
     */
    'estimatedOrderDuration': CaseDocumentEstimatedOrderDurationEnum;
    /**
     * Is the date when the document was first fetched from the court site.
     * @type {string}
     * @memberof CaseDocument
     */
    'firstFetchDate': string;
    /**
     * Determines if the document is present in the UniCourt Library or not.
     * @type {boolean}
     * @memberof CaseDocument
     */
    'inLibrary': boolean;
    /**
     * Determines if a preview is available for the case document.
     * @type {boolean}
     * @memberof CaseDocument
     */
    'isPreviewAvailable': boolean;
    /**
     * Document name.
     * @type {string}
     * @memberof CaseDocument
     */
    'name': string | null;
    /**
     * Name of the object
     * @type {string}
     * @memberof CaseDocument
     */
    'object': string;
    /**
     * Total number of pages in the document.
     * @type {number}
     * @memberof CaseDocument
     */
    'pages': number | null;
    /**
     * Document ID which is the parent document for the current document. This will be null if the current document is a parent document.
     * @type {string}
     * @memberof CaseDocument
     */
    'parentDocumentId': string | null;
    /**
     * 
     * @type {PreviewDocument}
     * @memberof CaseDocument
     */
    'previewDocument': PreviewDocument | null;
    /**
     * Price of the document.
     * @type {number}
     * @memberof CaseDocument
     */
    'price': number | null;
    /**
     * Order of documents how it is being stored in UniCourt.
     * @type {number}
     * @memberof CaseDocument
     */
    'sortOrder': number | null;
    /**
     * The status of source data of document. If the value of sourceDataStatus is SOURCE_DEPRECATED then it means that the Document has been migrated from old court site to a new court site and the data being shown in the API response is from a old court site. If the sourceDataStatus is NO_LONGER_AVAILABLE_IN_COURT then it means that a particular case is invalid in the court site.
     * @type {string}
     * @memberof CaseDocument
     */
    'sourceDataStatus': CaseDocumentSourceDataStatusEnum;
}

type CaseDocumentEstimatedOrderDurationEnum = 'estimateUnavailable' | 'withinMinutes' | 'withinHours' | 'withinDays' | 'withinWeeks'
type CaseDocumentSourceDataStatusEnum = 'NO_LONGER_AVAILABLE_IN_COURT' | 'SOURCE_DEPRECATED' | 'SEALED' | 'null'


