/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseCountAnalyticsByPartyRole } from './case-count-analytics-by-party-role';

/**
 * Case Count by Party Type Response.
 * @export
 * @interface CaseCountAnalyticsByPartyRoleResponse
 */
export interface CaseCountAnalyticsByPartyRoleResponse {
    /**
     * Next page of results if applicable.
     * @type {string}
     * @memberof CaseCountAnalyticsByPartyRoleResponse
     */
    'nextPageAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByPartyRoleResponse
     */
    'object': string;
    /**
     * Link to previous page of results.
     * @type {string}
     * @memberof CaseCountAnalyticsByPartyRoleResponse
     */
    'previousPageAPI': string | null;
    /**
     * 
     * @type {Array<CaseCountAnalyticsByPartyRole>}
     * @memberof CaseCountAnalyticsByPartyRoleResponse
     */
    'results': Array<CaseCountAnalyticsByPartyRole>;
    /**
     * Total no. of Cases for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByPartyRoleResponse
     */
    'totalCaseCount': number;
    /**
     * Total no. of pages.
     * @type {number}
     * @memberof CaseCountAnalyticsByPartyRoleResponse
     */
    'totalPages': number;
    /**
     * Total no. of Party Role for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByPartyRoleResponse
     */
    'totalPartyRoleCount': number;
}

