/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Count of each entitiy of a case is mentioned here so that you can calculate the number of requests needs to be done to obtain each entity results completely.
 * @export
 * @interface CaseStats
 */
export interface CaseStats {
    /**
     * Count which includes the freeCaseDocumentCount and paidCaseDocumentCount.
     * @type {number}
     * @memberof CaseStats
     */
    'allCaseDocumentCount': number;
    /**
     * Count of number of attornies available in the case being requested for.
     * @type {number}
     * @memberof CaseStats
     */
    'attorneyCount': number;
    /**
     * Count of number of documents that are available in the UniCourt CrowdSourced Library for the case being requested for.
     * @type {number}
     * @memberof CaseStats
     */
    'caseDocumentInLibraryCount': number;
    /**
     * Count of number of docket entries available in the case being requested for.
     * @type {number}
     * @memberof CaseStats
     */
    'docketEntryCount': number;
    /**
     * Count of number of free documents available in the case being requested for.
     * @type {number}
     * @memberof CaseStats
     */
    'freeCaseDocumentCount': number;
    /**
     * Count of number of hearings available in the case being requested for.
     * @type {number}
     * @memberof CaseStats
     */
    'hearingCount': number;
    /**
     * Count of number of judges available in the case being requested for.
     * @type {number}
     * @memberof CaseStats
     */
    'judgeCount': number;
    /**
     * Name of the object
     * @type {string}
     * @memberof CaseStats
     */
    'object': string;
    /**
     * Count of number of paid documents available in the case being requested for.
     * @type {number}
     * @memberof CaseStats
     */
    'paidCaseDocumentCount': number;
    /**
     * Count of number of parties available in the case being requested for.
     * @type {number}
     * @memberof CaseStats
     */
    'partyCount': number;
    /**
     * Count of related cases that are available in the case being requested.
     * @type {number}
     * @memberof CaseStats
     */
    'relatedCaseCount': number;
}

