/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseCountAnalyticsByCaseType } from './case-count-analytics-by-case-type';

/**
 * Case Counts by Case Types Response.
 * @export
 * @interface CaseCountAnalyticsByCaseTypeResponse
 */
export interface CaseCountAnalyticsByCaseTypeResponse {
    /**
     * Next page of results if applicable.
     * @type {string}
     * @memberof CaseCountAnalyticsByCaseTypeResponse
     */
    'nextPageAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByCaseTypeResponse
     */
    'object': string;
    /**
     * Link to previous page of results.
     * @type {string}
     * @memberof CaseCountAnalyticsByCaseTypeResponse
     */
    'previousPageAPI': string | null;
    /**
     * 
     * @type {Array<CaseCountAnalyticsByCaseType>}
     * @memberof CaseCountAnalyticsByCaseTypeResponse
     */
    'results': Array<CaseCountAnalyticsByCaseType>;
    /**
     * Total no. of Cases for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByCaseTypeResponse
     */
    'totalCaseCount': number;
    /**
     * Total no. of CaseType for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByCaseTypeResponse
     */
    'totalCaseTypeCount': number;
    /**
     * Total no. of pages.
     * @type {number}
     * @memberof CaseCountAnalyticsByCaseTypeResponse
     */
    'totalPages': number;
}

