/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseType } from './case-type';

/**
 * 
 * @export
 * @interface CaseCountAnalyticsByCaseType
 */
export interface CaseCountAnalyticsByCaseType {
    /**
     * 
     * @type {number}
     * @memberof CaseCountAnalyticsByCaseType
     */
    'caseCount': number;
    /**
     * Link to cases for this criteria.
     * @type {string}
     * @memberof CaseCountAnalyticsByCaseType
     */
    'caseSearchAPI': string;
    /**
     * 
     * @type {CaseType}
     * @memberof CaseCountAnalyticsByCaseType
     */
    'caseType': CaseType | null;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByCaseType
     */
    'object': string;
}

