/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CaseUpdatePacerOptionsResponseAdditionalPageArrayInner
 */
export interface CaseUpdatePacerOptionsResponseAdditionalPageArrayInner {
    /**
     * You can limit how often this page information is fetched to reduce your PACER fees.  Min days is 0 and Max days is 100.  Example: 1.  Specifying a value of 0 ensures that this page is fetched from PACER for this case update irrespective of when the page was last fetched. 2.  Specifying a value of 30 ensures that this page is fetched from PACER for this case update only if the last fetch was older than 30 days. 
     * @type {number}
     * @memberof CaseUpdatePacerOptionsResponseAdditionalPageArrayInner
     */
    'fetchIfOlderThanDays'?: number;
    /**
     * 
     * @type {string}
     * @memberof CaseUpdatePacerOptionsResponseAdditionalPageArrayInner
     */
    'page'?: CaseUpdatePacerOptionsResponseAdditionalPageArrayInnerPageEnum;
}

type CaseUpdatePacerOptionsResponseAdditionalPageArrayInnerPageEnum = 'associatedCases' | 'caseSummary' | 'listOfCreditors'


