/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseClass } from './case-class';

/**
 * 
 * @export
 * @interface CaseClassCoverage
 */
export interface CaseClassCoverage {
    /**
     * 
     * @type {CaseClass}
     * @memberof CaseClassCoverage
     */
    'caseClass': CaseClass;
    /**
     * Total Cases for a specific CourtLocation.
     * @type {number}
     * @memberof CaseClassCoverage
     */
    'caseCount': number;
    /**
     * Case Documents that were added to UniCourt Crowd Source Library for a specific CourtLocationy.
     * @type {number}
     * @memberof CaseClassCoverage
     */
    'caseDocumentInLibraryCount': number;
    /**
     * Case Documents that were added to UniCourt Crowd Source Library for a specific CourtLocation in last 30 days.
     * @type {number}
     * @memberof CaseClassCoverage
     */
    'caseDocumentInLibraryInLastThirtyDaysCount': number;
    /**
     * Cases in last 30 days that were added to UniCourt for a specific CourtLocation
     * @type {number}
     * @memberof CaseClassCoverage
     */
    'casesInLastThirtyDaysCount': number;
    /**
     * API Link to the Court Service status with filters of court and case class
     * @type {string}
     * @memberof CaseClassCoverage
     */
    'courtServiceStatusAPI': string;
    /**
     * Free Case Documents for a specific CourtLocation.
     * @type {number}
     * @memberof CaseClassCoverage
     */
    'freeCaseDocumentCount': number;
    /**
     * Free Case Documents in last 30 days that were added to UniCourt for a specific CourtLocation.
     * @type {number}
     * @memberof CaseClassCoverage
     */
    'freeCaseDocumentsInLastThirtyDaysCount': number;
    /**
     * Name of the object
     * @type {string}
     * @memberof CaseClassCoverage
     */
    'object': string;
    /**
     * Paid Case Documents for a specific CourtLocation.
     * @type {number}
     * @memberof CaseClassCoverage
     */
    'paidCaseDocumentCount': number;
    /**
     * Paid Case Documents in last 30 days that were added to UniCourt for a specific CourtLocation.
     * @type {number}
     * @memberof CaseClassCoverage
     */
    'paidCaseDocumentsInLastThirtyDaysCount': number;
}

