/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CaseCountAnalyticsByNormJudge
 */
export interface CaseCountAnalyticsByNormJudge {
    /**
     * 
     * @type {number}
     * @memberof CaseCountAnalyticsByNormJudge
     */
    'caseCount': number;
    /**
     * Link to cases for this criteria.
     * @type {string}
     * @memberof CaseCountAnalyticsByNormJudge
     */
    'caseSearchAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByNormJudge
     */
    'normJudgeId': string;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByNormJudge
     */
    'normJudgeName': string;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByNormJudge
     */
    'object': string;
}

