/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseDocumentOrderCallback } from './case-document-order-callback';

/**
 * 
 * @export
 * @interface CaseDocumentOrderCallbackListResponse
 */
export interface CaseDocumentOrderCallbackListResponse {
    /**
     * Array of case document order callback objects.
     * @type {Array<CaseDocumentOrderCallback>}
     * @memberof CaseDocumentOrderCallbackListResponse
     */
    'callbackArray': Array<CaseDocumentOrderCallback>;
    /**
     * Link for the next page.
     * @type {string}
     * @memberof CaseDocumentOrderCallbackListResponse
     */
    'nextPageAPI': string | null;
    /**
     * Name of the object.
     * @type {string}
     * @memberof CaseDocumentOrderCallbackListResponse
     */
    'object': string;
    /**
     * Current page number.
     * @type {number}
     * @memberof CaseDocumentOrderCallbackListResponse
     */
    'pageNumber': number;
    /**
     * Link for the previous page.
     * @type {string}
     * @memberof CaseDocumentOrderCallbackListResponse
     */
    'previousPageAPI': string | null;
    /**
     * Total number of case document order callback objects available.
     * @type {number}
     * @memberof CaseDocumentOrderCallbackListResponse
     */
    'totalCount': number;
    /**
     * Total number of pages available.
     * @type {number}
     * @memberof CaseDocumentOrderCallbackListResponse
     */
    'totalPages': number;
}

