/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PartyRoleGroup } from './party-role-group';

/**
 * 
 * @export
 * @interface CaseCountAnalyticsByPartyRoleGroup
 */
export interface CaseCountAnalyticsByPartyRoleGroup {
    /**
     * 
     * @type {number}
     * @memberof CaseCountAnalyticsByPartyRoleGroup
     */
    'caseCount': number;
    /**
     * Link to cases for the entity involving the search criteria. TBD.
     * @type {string}
     * @memberof CaseCountAnalyticsByPartyRoleGroup
     */
    'caseSearchAPI': string;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByPartyRoleGroup
     */
    'object': string;
    /**
     * 
     * @type {PartyRoleGroup}
     * @memberof CaseCountAnalyticsByPartyRoleGroup
     */
    'partyRoleGroup': PartyRoleGroup;
}

