/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseRelationshipType } from './case-relationship-type';

/**
 * 
 * @export
 * @interface CaseRelationshipTypeResponse
 */
export interface CaseRelationshipTypeResponse {
    /**
     * 
     * @type {Array<CaseRelationshipType>}
     * @memberof CaseRelationshipTypeResponse
     */
    'caseRelationshipTypeArray': Array<CaseRelationshipType>;
    /**
     * Link to next page.
     * @type {string}
     * @memberof CaseRelationshipTypeResponse
     */
    'nextPageAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CaseRelationshipTypeResponse
     */
    'object': string;
    /**
     * Page number for which results where obtained.
     * @type {number}
     * @memberof CaseRelationshipTypeResponse
     */
    'pageNumber': number;
    /**
     * Link to previous page.
     * @type {string}
     * @memberof CaseRelationshipTypeResponse
     */
    'previousPageAPI': string | null;
    /**
     * Total number of matches found.
     * @type {number}
     * @memberof CaseRelationshipTypeResponse
     */
    'totalCount': number;
    /**
     * Total number of pages to obtain all the objects.
     * @type {number}
     * @memberof CaseRelationshipTypeResponse
     */
    'totalPages': number;
}

