/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseCountAnalyticsByJurisdictionGeo } from './case-count-analytics-by-jurisdiction-geo';

/**
 * Case Counts by Juridiction Geo Response.
 * @export
 * @interface CaseCountAnalyticsByJurisdictionGeoResponse
 */
export interface CaseCountAnalyticsByJurisdictionGeoResponse {
    /**
     * Next page of results if applicable.
     * @type {string}
     * @memberof CaseCountAnalyticsByJurisdictionGeoResponse
     */
    'nextPageAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByJurisdictionGeoResponse
     */
    'object': string;
    /**
     * Link to previous page of results.
     * @type {string}
     * @memberof CaseCountAnalyticsByJurisdictionGeoResponse
     */
    'previousPageAPI': string | null;
    /**
     * 
     * @type {Array<CaseCountAnalyticsByJurisdictionGeo>}
     * @memberof CaseCountAnalyticsByJurisdictionGeoResponse
     */
    'results': Array<CaseCountAnalyticsByJurisdictionGeo>;
    /**
     * Total no. of Cases for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByJurisdictionGeoResponse
     */
    'totalCaseCount': number;
    /**
     * Total no. of Jurisdiction for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByJurisdictionGeoResponse
     */
    'totalJurisdictionGeoCount': number;
    /**
     * Total no. of pages.
     * @type {number}
     * @memberof CaseCountAnalyticsByJurisdictionGeoResponse
     */
    'totalPages': number;
}

