/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseCountAnalyticsByNormParty } from './case-count-analytics-by-norm-party';

/**
 * 
 * @export
 * @interface CaseCountAnalyticsByNormPartyResponse
 */
export interface CaseCountAnalyticsByNormPartyResponse {
    /**
     * Next page of results if applicable.
     * @type {string}
     * @memberof CaseCountAnalyticsByNormPartyResponse
     */
    'nextPageAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CaseCountAnalyticsByNormPartyResponse
     */
    'object': string;
    /**
     * Link to previous page of results.
     * @type {string}
     * @memberof CaseCountAnalyticsByNormPartyResponse
     */
    'previousPageAPI': string | null;
    /**
     * 
     * @type {Array<CaseCountAnalyticsByNormParty>}
     * @memberof CaseCountAnalyticsByNormPartyResponse
     */
    'results': Array<CaseCountAnalyticsByNormParty>;
    /**
     * Total no. of Cases for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByNormPartyResponse
     */
    'totalCaseCount': number;
    /**
     * Total no. of NormParty for this criteria.
     * @type {number}
     * @memberof CaseCountAnalyticsByNormPartyResponse
     */
    'totalNormPartyCount': number;
    /**
     * Total no. of pages.
     * @type {number}
     * @memberof CaseCountAnalyticsByNormPartyResponse
     */
    'totalPages': number;
}

