/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CauseOfActionAdditionalData } from './cause-of-action-additional-data';

/**
 * 
 * @export
 * @interface CauseOfActionAdditionalDataResponse
 */
export interface CauseOfActionAdditionalDataResponse {
    /**
     * 
     * @type {Array<CauseOfActionAdditionalData>}
     * @memberof CauseOfActionAdditionalDataResponse
     */
    'causeOfActionAdditionalDataArray': Array<CauseOfActionAdditionalData>;
    /**
     * Link to next page.
     * @type {string}
     * @memberof CauseOfActionAdditionalDataResponse
     */
    'nextPageAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CauseOfActionAdditionalDataResponse
     */
    'object': string;
    /**
     * Page number for which results where obtained.
     * @type {number}
     * @memberof CauseOfActionAdditionalDataResponse
     */
    'pageNumber': number;
    /**
     * Link to previous page.
     * @type {string}
     * @memberof CauseOfActionAdditionalDataResponse
     */
    'previousPageAPI': string | null;
    /**
     * Total number of matches found.
     * @type {number}
     * @memberof CauseOfActionAdditionalDataResponse
     */
    'totalCount': number;
    /**
     * Total number of pages to obtain all the objects.
     * @type {number}
     * @memberof CauseOfActionAdditionalDataResponse
     */
    'totalPages': number;
}

