/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ChargeDegree
 */
export interface ChargeDegree {
    /**
     * 
     * @type {string}
     * @memberof ChargeDegree
     */
    'chargeDegreeId': string;
    /**
     * The date and time when it was first created. This date and time is in UTC. Formatted as YYYY-MM-DD HH:MM:SS.
     * @type {string}
     * @memberof ChargeDegree
     */
    'createdDate': string;
    /**
     * 
     * @type {string}
     * @memberof ChargeDegree
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ChargeDegree
     */
    'object': string;
}

