/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChargeAdditionalData } from './charge-additional-data';

/**
 * 
 * @export
 * @interface ChargeAdditionalDataResponse
 */
export interface ChargeAdditionalDataResponse {
    /**
     * 
     * @type {Array<ChargeAdditionalData>}
     * @memberof ChargeAdditionalDataResponse
     */
    'chargeAdditionalDataArray': Array<ChargeAdditionalData>;
    /**
     * Link to next page.
     * @type {string}
     * @memberof ChargeAdditionalDataResponse
     */
    'nextPageAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof ChargeAdditionalDataResponse
     */
    'object': string;
    /**
     * Page number for which results where obtained.
     * @type {number}
     * @memberof ChargeAdditionalDataResponse
     */
    'pageNumber': number;
    /**
     * Link to previous page.
     * @type {string}
     * @memberof ChargeAdditionalDataResponse
     */
    'previousPageAPI': string | null;
    /**
     * Total number of matches found.
     * @type {number}
     * @memberof ChargeAdditionalDataResponse
     */
    'totalCount': number;
    /**
     * Total number of pages to obtain all the objects.
     * @type {number}
     * @memberof ChargeAdditionalDataResponse
     */
    'totalPages': number;
}

