/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Email } from './email';
import { Phone } from './phone';

/**
 * Contact object data schema.
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * List of available addresses.
     * @type {Array<Address>}
     * @memberof Contact
     */
    'addressArray': Array<Address> | null;
    /**
     * List of available emails.
     * @type {Array<Email>}
     * @memberof Contact
     */
    'emailArray': Array<Email> | null;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    'object': string;
    /**
     * List of available phone numbers.
     * @type {Array<Phone>}
     * @memberof Contact
     */
    'phoneNumberArray': Array<Phone> | null;
}

