/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CourtLocation
 */
export interface CourtLocation {
    /**
     * City
     * @type {string}
     * @memberof CourtLocation
     */
    'city': string | null;
    /**
     * 
     * @type {string}
     * @memberof CourtLocation
     */
    'courtLocationId': string;
    /**
     * 
     * @type {string}
     * @memberof CourtLocation
     */
    'courtServiceStatusAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof CourtLocation
     */
    'courtsForCourtLocationAPI': string;
    /**
     * The date and time when it was first created. This date and time is in UTC. Formatted as YYYY-MM-DD HH:MM:SS.
     * @type {string}
     * @memberof CourtLocation
     */
    'createdDate': string;
    /**
     * 
     * @type {string}
     * @memberof CourtLocation
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CourtLocation
     */
    'object': string;
    /**
     * State Name if present else default value.
     * @type {string}
     * @memberof CourtLocation
     */
    'stateName': string;
    /**
     * 1st part of the street address.
     * @type {string}
     * @memberof CourtLocation
     */
    'streetAddress1': string | null;
    /**
     * 2nd part of the street address.
     * @type {string}
     * @memberof CourtLocation
     */
    'streetAddress2': string | null;
}

