/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Total API calls made for the billing cycle.
 * @export
 * @interface DailyUsageResponseApiCallsMade
 */
export interface DailyUsageResponseApiCallsMade {
    /**
     * Total API calls made for the billing cycle
     * @type {number}
     * @memberof DailyUsageResponseApiCallsMade
     */
    'count': number;
    /**
     * Last Updated date and time for the field apiCallsMade
     * @type {string}
     * @memberof DailyUsageResponseApiCallsMade
     */
    'lastUpdated': string | null;
}

