/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseDocument } from './case-document';

/**
 * Secondary Documents refers to documents that are attached to a docket entry. Secondary Documents could be specific to a courts or case type in courts. For isntance the below example is in PACER. PACER District Courts - Here the secondary document is one which is attached in the docket entry.
 * @export
 * @interface DocketEntrySecondaryDocuments
 */
export interface DocketEntrySecondaryDocuments {
    /**
     * 
     * @type {Array<CaseDocument>}
     * @memberof DocketEntrySecondaryDocuments
     */
    'caseDocumentArray': Array<CaseDocument>;
    /**
     * Link to next page of a particular entity in a Case.
     * @type {string}
     * @memberof DocketEntrySecondaryDocuments
     */
    'nextPageAPI': string | null;
    /**
     * Name of the object
     * @type {string}
     * @memberof DocketEntrySecondaryDocuments
     */
    'object': string;
    /**
     * Page number for which results where obtained.
     * @type {number}
     * @memberof DocketEntrySecondaryDocuments
     */
    'pageNumber': number;
    /**
     * Total number of parties of the Case. entity in a Case.
     * @type {number}
     * @memberof DocketEntrySecondaryDocuments
     */
    'totalCount': number;
    /**
     * Total number of pages to obtain all the objects of a party in the Case.
     * @type {number}
     * @memberof DocketEntrySecondaryDocuments
     */
    'totalPages': number;
}

