/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Exception object contains specific error code and its message related to the API request validation error or error occurred during API request processing.
 * @export
 * @interface Exception
 */
export interface Exception {
    /**
     * Indicates the type of error occured.
     * @type {string}
     * @memberof Exception
     */
    'code': string;
    /**
     * Describes what went wrong.
     * @type {string}
     * @memberof Exception
     */
    'details': string;
    /**
     * Indicates the error message that describes the error code.
     * @type {string}
     * @memberof Exception
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof Exception
     */
    'object': string;
}

