/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SourceStructuredData } from './source-structured-data';

/**
 * 
 * @export
 * @interface Hearing
 */
export interface Hearing {
    /**
     * When this hearing was first fetched from the source.
     * @type {string}
     * @memberof Hearing
     */
    'firstFetchDate': string;
    /**
     * Hearing Date
     * @type {string}
     * @memberof Hearing
     */
    'hearingDate': string;
    /**
     * Source Hearing Description Text
     * @type {string}
     * @memberof Hearing
     */
    'hearingDescription': string | null;
    /**
     * 
     * @type {SourceStructuredData}
     * @memberof Hearing
     */
    'hearingStructured': SourceStructuredData | null;
    /**
     * When this hearing was last fetched from the source.
     * @type {string}
     * @memberof Hearing
     */
    'lastFetchDate': string;
    /**
     * Location where the hearing will takeplace.
     * @type {string}
     * @memberof Hearing
     */
    'location': string | null;
    /**
     * Name of the object
     * @type {string}
     * @memberof Hearing
     */
    'object': string;
}

