/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * * Only applicable if the Party is an Individual. 
 * @export
 * @interface IndividualProperty
 */
export interface IndividualProperty {
    /**
     * 
     * @type {string}
     * @memberof IndividualProperty
     */
    'firstName': string | null;
    /**
     * 
     * @type {string}
     * @memberof IndividualProperty
     */
    'lastName': string | null;
    /**
     * 
     * @type {string}
     * @memberof IndividualProperty
     */
    'middleName': string | null;
    /**
     * 
     * @type {string}
     * @memberof IndividualProperty
     */
    'name': string | null;
}

