/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InvalidateAccessTokenRequest
 */
export interface InvalidateAccessTokenRequest {
    /**
     * Your Client ID obtainable by logging into your UniCourt account.
     * @type {string}
     * @memberof InvalidateAccessTokenRequest
     */
    'clientId': string;
    /**
     * Your Client Secret ID obtainable by logging into your UniCourt account.
     * @type {string}
     * @memberof InvalidateAccessTokenRequest
     */
    'clientSecret': string;
    /**
     * The Token ID of token being invalidated
     * @type {string}
     * @memberof InvalidateAccessTokenRequest
     */
    'tokenId': string;
}

