/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface JudgeAnalyticsAPI
 */
export interface JudgeAnalyticsAPI {
    /**
     * 
     * @type {string}
     * @memberof JudgeAnalyticsAPI
     */
    'associatedNormAttorneysAPI': string;
    /**
     * 
     * @type {string}
     * @memberof JudgeAnalyticsAPI
     */
    'associatedNormLawFirmsAPI': string;
    /**
     * 
     * @type {string}
     * @memberof JudgeAnalyticsAPI
     */
    'associatedNormPartiesAPI': string;
    /**
     * Link to Details for the Judge.
     * @type {string}
     * @memberof JudgeAnalyticsAPI
     */
    'normJudgeAPI': string;
    /**
     * 
     * @type {string}
     * @memberof JudgeAnalyticsAPI
     */
    'object': string;
}

