/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseUpdatePacerOptionsResponse } from './case-update-pacer-options-response';
import { Exception } from './exception';

/**
 * 
 * @export
 * @interface LastTrackedDetails
 */
export interface LastTrackedDetails {
    /**
     * The date and time when the case was tracked for this account.
     * @type {string}
     * @memberof LastTrackedDetails
     */
    'lastTrackDate': string | null;
    /**
     * 
     * @type {Exception}
     * @memberof LastTrackedDetails
     */
    'lastTrackException': Exception | null;
    /**
     * Name of the object.
     * @type {string}
     * @memberof LastTrackedDetails
     */
    'object': string;
    /**
     * 
     * @type {CaseUpdatePacerOptionsResponse}
     * @memberof LastTrackedDetails
     */
    'pacerOptions': CaseUpdatePacerOptionsResponse | null;
}

