/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LawFirmAnalyticsAPI
 */
export interface LawFirmAnalyticsAPI {
    /**
     * 
     * @type {string}
     * @memberof LawFirmAnalyticsAPI
     */
    'associatedNormAttorneyAPI': string;
    /**
     * 
     * @type {string}
     * @memberof LawFirmAnalyticsAPI
     */
    'associatedNormJudgeAPI': string;
    /**
     * 
     * @type {string}
     * @memberof LawFirmAnalyticsAPI
     */
    'associatedNormPartiesAPI': string;
    /**
     * 
     * @type {string}
     * @memberof LawFirmAnalyticsAPI
     */
    'caseCountAnalyticsByOpposingNormAttorneyAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof LawFirmAnalyticsAPI
     */
    'caseCountAnalyticsByOpposingNormLawFirmAPI': string;
    /**
     * 
     * @type {string}
     * @memberof LawFirmAnalyticsAPI
     */
    'caseCountAnalyticsByOpposingNormPartyAPI': string | null;
    /**
     * Link to Details for the Law Firm.
     * @type {string}
     * @memberof LawFirmAnalyticsAPI
     */
    'normLawFirmAPI': string;
    /**
     * 
     * @type {string}
     * @memberof LawFirmAnalyticsAPI
     */
    'object': string;
}

