/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MatchedObject
 */
export interface MatchedObject {
    /**
     * 
     * @type {string}
     * @memberof MatchedObject
     */
    'highlightSnippet': string;
    /**
     * 
     * @type {string}
     * @memberof MatchedObject
     */
    'matchedObjectAPI': string;
    /**
     * 
     * @type {string}
     * @memberof MatchedObject
     */
    'matchedObjectAttribute': string;
    /**
     * 
     * @type {string}
     * @memberof MatchedObject
     */
    'matchedObjectId': string;
    /**
     * 
     * @type {string}
     * @memberof MatchedObject
     */
    'matchedObjectName': string;
    /**
     * 
     * @type {string}
     * @memberof MatchedObject
     */
    'object': string;
}

