/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Nature Of Suit for a case.
 * @export
 * @interface NatureOfSuit
 */
export interface NatureOfSuit {
    /**
     * Nos Code from the source site which is extracted from the sourceText.
     * @type {number}
     * @memberof NatureOfSuit
     */
    'code': number;
    /**
     * Code Name from the source site which is extracted from the sourceText.
     * @type {string}
     * @memberof NatureOfSuit
     */
    'name': string | null;
    /**
     * Name of the object
     * @type {string}
     * @memberof NatureOfSuit
     */
    'object': string;
    /**
     * Section of a nos code extracted from the sourceText.
     * @type {string}
     * @memberof NatureOfSuit
     */
    'section': string | null;
    /**
     * Source nos code data from the court site.
     * @type {string}
     * @memberof NatureOfSuit
     */
    'sourceText': string | null;
}

