/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseAnalyticsAPI } from './case-analytics-api';
import { LawFirmAnalyticsAPI } from './law-firm-analytics-api';
import { NormOrganization } from './norm-organization';

/**
 * Schema for Norm Law Firm containing Organization sub-field.
 * @export
 * @interface NormLawFirm
 */
export interface NormLawFirm {
    /**
     * 
     * @type {CaseAnalyticsAPI}
     * @memberof NormLawFirm
     */
    'caseAnalyticsAPI': CaseAnalyticsAPI;
    /**
     * 
     * @type {string}
     * @memberof NormLawFirm
     */
    'caseSearchAPI': string;
    /**
     * 
     * @type {LawFirmAnalyticsAPI}
     * @memberof NormLawFirm
     */
    'lawFirmAnalyticsAPI': LawFirmAnalyticsAPI;
    /**
     * 
     * @type {string}
     * @memberof NormLawFirm
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof NormLawFirm
     */
    'normLawFirmId': string;
    /**
     * 
     * @type {NormOrganization}
     * @memberof NormLawFirm
     */
    'normOrganizationData': NormOrganization;
    /**
     * 
     * @type {string}
     * @memberof NormLawFirm
     */
    'object': string;
}

