/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CaseAnalyticsAPI } from './case-analytics-api';
import { IndividualProperty } from './individual-property';
import { NormOrganization } from './norm-organization';
import { PartyAnalyticsAPI } from './party-analytics-api';
import { RelatedNormParty } from './related-norm-party';

/**
 * Norm Party
 * @export
 * @interface NormParty
 */
export interface NormParty {
    /**
     * 
     * @type {CaseAnalyticsAPI}
     * @memberof NormParty
     */
    'caseAnalyticsAPI': CaseAnalyticsAPI;
    /**
     * 
     * @type {string}
     * @memberof NormParty
     */
    'caseSearchAPI': string;
    /**
     * 
     * @type {IndividualProperty}
     * @memberof NormParty
     */
    'individualData': IndividualProperty | null;
    /**
     * 
     * @type {string}
     * @memberof NormParty
     */
    'name': string;
    /**
     * 
     * @type {NormOrganization}
     * @memberof NormParty
     */
    'normOrganizationData': NormOrganization;
    /**
     * 
     * @type {string}
     * @memberof NormParty
     */
    'normPartyId': string;
    /**
     * 
     * @type {string}
     * @memberof NormParty
     */
    'object': string;
    /**
     * 
     * @type {PartyAnalyticsAPI}
     * @memberof NormParty
     */
    'partyAnalyticsAPI': PartyAnalyticsAPI;
    /**
     * 
     * @type {string}
     * @memberof NormParty
     */
    'partyClassificationType': NormPartyPartyClassificationTypeEnum;
    /**
     * 
     * @type {Array<RelatedNormParty>}
     * @memberof NormParty
     */
    'relatedNormPartyArray': Array<RelatedNormParty>;
}

type NormPartyPartyClassificationTypeEnum = 'Individual' | 'Organization'


