/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Contact } from './contact';
import { NormJudgePublicDataAbaRatings } from './norm-judge-public-data-aba-ratings';
import { NormJudgePublicDataBio } from './norm-judge-public-data-bio';
import { NormJudgePublicDataEducationArrayInner } from './norm-judge-public-data-education-array-inner';
import { NormJudgePublicDataJudicialSource } from './norm-judge-public-data-judicial-source';
import { NormJudgePublicDataNameHistoryArrayInner } from './norm-judge-public-data-name-history-array-inner';
import { ServiceHistory } from './service-history';

/**
 * This contains the Judge Public details that is obtained from various sources.
 * @export
 * @interface NormJudgePublicData
 */
export interface NormJudgePublicData {
    /**
     * 
     * @type {NormJudgePublicDataAbaRatings}
     * @memberof NormJudgePublicData
     */
    'abaRatings': NormJudgePublicDataAbaRatings | null;
    /**
     * Other Names of the Judge.
     * @type {Array<string>}
     * @memberof NormJudgePublicData
     */
    'aliasArray': Array<string>;
    /**
     * 
     * @type {NormJudgePublicDataBio}
     * @memberof NormJudgePublicData
     */
    'bio': NormJudgePublicDataBio;
    /**
     * 
     * @type {Contact}
     * @memberof NormJudgePublicData
     */
    'contact': Contact;
    /**
     * The Education History of the judge.
     * @type {Array<NormJudgePublicDataEducationArrayInner>}
     * @memberof NormJudgePublicData
     */
    'educationArray': Array<NormJudgePublicDataEducationArrayInner>;
    /**
     * 
     * @type {string}
     * @memberof NormJudgePublicData
     */
    'firstFetchDate': string | null;
    /**
     * 
     * @type {NormJudgePublicDataJudicialSource}
     * @memberof NormJudgePublicData
     */
    'judicialSource': NormJudgePublicDataJudicialSource;
    /**
     * The judicial status of the Judge
     * @type {string}
     * @memberof NormJudgePublicData
     */
    'judicialStatus': string | null;
    /**
     * 
     * @type {string}
     * @memberof NormJudgePublicData
     */
    'lastFetchDate': string | null;
    /**
     * Last Fetch Date of the Judge Update.
     * @type {string}
     * @memberof NormJudgePublicData
     */
    'lastFetchDateWithUpdates': string | null;
    /**
     * Name changes of the Judge. Change in the official name. Other names go to Alias array.
     * @type {Array<NormJudgePublicDataNameHistoryArrayInner>}
     * @memberof NormJudgePublicData
     */
    'nameHistoryArray': Array<NormJudgePublicDataNameHistoryArrayInner>;
    /**
     * 
     * @type {string}
     * @memberof NormJudgePublicData
     */
    'object': string;
    /**
     * The non-judicial career history of the judge.
     * @type {Array<string>}
     * @memberof NormJudgePublicData
     */
    'professionalCareerArray': Array<string>;
    /**
     * Judicial History of the Judge.
     * @type {Array<ServiceHistory>}
     * @memberof NormJudgePublicData
     */
    'serviceHistoryArray': Array<ServiceHistory>;
}

