/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NormJudgePublicDataEducationArrayInner
 */
export interface NormJudgePublicDataEducationArrayInner {
    /**
     * The Degree Awarded to the Judge
     * @type {string}
     * @memberof NormJudgePublicDataEducationArrayInner
     */
    'degree': string | null;
    /**
     * The University which awarded the degree to the Judge.
     * @type {string}
     * @memberof NormJudgePublicDataEducationArrayInner
     */
    'school': string | null;
    /**
     * The year when the degree was awarded.
     * @type {number}
     * @memberof NormJudgePublicDataEducationArrayInner
     */
    'year': number | null;
}

