/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The judicial source of the Judge
 * @export
 * @interface NormJudgePublicDataJudicialSource
 */
export interface NormJudgePublicDataJudicialSource {
    /**
     * Name of the Judicial Data Source
     * @type {string}
     * @memberof NormJudgePublicDataJudicialSource
     */
    'name': string;
    /**
     * Type of acquisition of the data source
     * @type {string}
     * @memberof NormJudgePublicDataJudicialSource
     */
    'type': NormJudgePublicDataJudicialSourceTypeEnum;
    /**
     * URL of the data source, if type is Website
     * @type {string}
     * @memberof NormJudgePublicDataJudicialSource
     */
    'url': string | null;
}

type NormJudgePublicDataJudicialSourceTypeEnum = 'Website' | 'Other'


