/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttorneyAnalyticsAPI } from './attorney-analytics-api';
import { BarRecord } from './bar-record';
import { CaseAnalyticsAPI } from './case-analytics-api';
import { SimilarNormAttorney } from './similar-norm-attorney';

/**
 * Norm Attorney
 * @export
 * @interface NormAttorney
 */
export interface NormAttorney {
    /**
     * 
     * @type {AttorneyAnalyticsAPI}
     * @memberof NormAttorney
     */
    'attorneyAnalyticsAPI': AttorneyAnalyticsAPI;
    /**
     * 
     * @type {Array<BarRecord>}
     * @memberof NormAttorney
     */
    'barRecordArray': Array<BarRecord>;
    /**
     * 
     * @type {CaseAnalyticsAPI}
     * @memberof NormAttorney
     */
    'caseAnalyticsAPI': CaseAnalyticsAPI;
    /**
     * 
     * @type {string}
     * @memberof NormAttorney
     */
    'caseSearchAPI': string;
    /**
     * 
     * @type {string}
     * @memberof NormAttorney
     */
    'firstName': string;
    /**
     * 
     * @type {boolean}
     * @memberof NormAttorney
     */
    'hasAssociatedPublicData': boolean;
    /**
     * 
     * @type {string}
     * @memberof NormAttorney
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof NormAttorney
     */
    'middleName': string | null;
    /**
     * 
     * @type {string}
     * @memberof NormAttorney
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof NormAttorney
     */
    'normAttorneyId': string;
    /**
     * 
     * @type {string}
     * @memberof NormAttorney
     */
    'object': string;
    /**
     * 
     * @type {Array<SimilarNormAttorney>}
     * @memberof NormAttorney
     */
    'similarNormAttorneyArray': Array<SimilarNormAttorney>;
}

