/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PACERSearchPageInfo
 */
export interface PACERSearchPageInfo {
    /**
     * Indicates if the current page is the first page.
     * @type {boolean}
     * @memberof PACERSearchPageInfo
     */
    'first': boolean;
    /**
     * Indicates if the current page is the last page.
     * @type {boolean}
     * @memberof PACERSearchPageInfo
     */
    'last': boolean;
    /**
     * Current Page number.
     * @type {number}
     * @memberof PACERSearchPageInfo
     */
    'number': number;
    /**
     * Number of records returned.
     * @type {number}
     * @memberof PACERSearchPageInfo
     */
    'numberOfElements': number;
    /**
     * Name of the object
     * @type {string}
     * @memberof PACERSearchPageInfo
     */
    'object': string;
    /**
     * Number of results obtained in a page..
     * @type {number}
     * @memberof PACERSearchPageInfo
     */
    'size': number;
    /**
     * Total number of records available
     * @type {number}
     * @memberof PACERSearchPageInfo
     */
    'totalElements': number;
    /**
     * Total pages of data available.
     * @type {number}
     * @memberof PACERSearchPageInfo
     */
    'totalPages': number;
}

