/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PACERSearchReceipt
 */
export interface PACERSearchReceipt {
    /**
     * Description of the search made.
     * @type {string}
     * @memberof PACERSearchReceipt
     */
    'description': string | null;
    /**
     * No of pages that was billed for the given PACER search.
     * @type {number}
     * @memberof PACERSearchReceipt
     */
    'billablePages': number;
    /**
     * client code added if any was set.
     * @type {string}
     * @memberof PACERSearchReceipt
     */
    'clientCode': string | null;
    /**
     * PACER Account ID.
     * @type {number}
     * @memberof PACERSearchReceipt
     */
    'csoId': number | null;
    /**
     * Firm ID.
     * @type {string}
     * @memberof PACERSearchReceipt
     */
    'firmId': string | null;
    /**
     * ID which is used for PACER login.
     * @type {string}
     * @memberof PACERSearchReceipt
     */
    'loginId': string;
    /**
     * Name of the object
     * @type {string}
     * @memberof PACERSearchReceipt
     */
    'object': string;
    /**
     * Report ID for the search made.
     * @type {string}
     * @memberof PACERSearchReceipt
     */
    'reportId': string | null;
    /**
     * Details of the search made for this request.
     * @type {string}
     * @memberof PACERSearchReceipt
     */
    'search': string | null;
    /**
     * PACER Search Fee.
     * @type {string}
     * @memberof PACERSearchReceipt
     */
    'searchFee': string;
    /**
     * Date when the transaction was made at the pacer court site.
     * @type {string}
     * @memberof PACERSearchReceipt
     */
    'transactionDate': string;
}

