/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PacerCredential
 */
export interface PacerCredential {
    /**
     * Pacer Client Code.
     * @type {string}
     * @memberof PacerCredential
     */
    'defaultPacerClientCode': string | null;
    /**
     * Name of the object.
     * @type {string}
     * @memberof PacerCredential
     */
    'object': string;
    /**
     * Pacer User Id.
     * @type {string}
     * @memberof PacerCredential
     */
    'pacerUserId': string;
}

