/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PartyAnalyticsAPI
 */
export interface PartyAnalyticsAPI {
    /**
     * 
     * @type {string}
     * @memberof PartyAnalyticsAPI
     */
    'associatedNormAttorneysAPI': string;
    /**
     * 
     * @type {string}
     * @memberof PartyAnalyticsAPI
     */
    'associatedNormJudgesAPI': string;
    /**
     * 
     * @type {string}
     * @memberof PartyAnalyticsAPI
     */
    'associatedNormLawFirmsAPI': string;
    /**
     * 
     * @type {string}
     * @memberof PartyAnalyticsAPI
     */
    'caseCountAnalyticsByOpposingNormAttorneyAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof PartyAnalyticsAPI
     */
    'caseCountAnalyticsByOpposingNormLawFirmAPI': string | null;
    /**
     * 
     * @type {string}
     * @memberof PartyAnalyticsAPI
     */
    'caseCountAnalyticsByOpposingNormPartyAPI': string;
    /**
     * Link to Details for the Party.
     * @type {string}
     * @memberof PartyAnalyticsAPI
     */
    'normPartyAPI': string;
    /**
     * 
     * @type {string}
     * @memberof PartyAnalyticsAPI
     */
    'object': string;
}

