/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PACERCaseSearchResults } from './pacercase-search-results';
import { PACERSearchPageInfo } from './pacersearch-page-info';
import { PACERSearchReceipt } from './pacersearch-receipt';

/**
 * 
 * @export
 * @interface PCLCase
 */
export interface PCLCase {
    /**
     * Link to next page of the PCL Search Results.
     * @type {string}
     * @memberof PCLCase
     */
    'nextPageAPI': string | null;
    /**
     * Name of the object
     * @type {string}
     * @memberof PCLCase
     */
    'object': string;
    /**
     * 
     * @type {PACERSearchPageInfo}
     * @memberof PCLCase
     */
    'pacerPageInfo': PACERSearchPageInfo;
    /**
     * 
     * @type {PACERSearchReceipt}
     * @memberof PCLCase
     */
    'pacerReceipt': PACERSearchReceipt;
    /**
     * 
     * @type {Array<PACERCaseSearchResults>}
     * @memberof PCLCase
     */
    'pacerSearchResultsArray': Array<PACERCaseSearchResults>;
    /**
     * Page number for which results where obtained.
     * @type {number}
     * @memberof PCLCase
     */
    'pageNumber': number;
    /**
     * Total number of records available for this Search.
     * @type {number}
     * @memberof PCLCase
     */
    'totalCount': number;
    /**
     * Total number of pages to obtain all the objects the current PCL Search.
     * @type {number}
     * @memberof PCLCase
     */
    'totalPages': number;
}

