/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PossibleNormLawFirmSourceDetails
 */
export interface PossibleNormLawFirmSourceDetails {
    /**
     * 
     * @type {Array<string>}
     * @memberof PossibleNormLawFirmSourceDetails
     */
    'linkedNormAttorneyIdArray': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormLawFirmSourceDetails
     */
    'source': PossibleNormLawFirmSourceDetailsSourceEnum;
}

type PossibleNormLawFirmSourceDetailsSourceEnum = 'Case_Attorney_Linked_In_Other_Cases' | 'Case_Attorney_Field_Contains_Law_Firm'


