/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PossibleNormJudgeScoreConstituents
 */
export interface PossibleNormJudgeScoreConstituents {
    /**
     * 
     * @type {string}
     * @memberof PossibleNormJudgeScoreConstituents
     */
    'address': PossibleNormJudgeScoreConstituentsAddressEnum;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormJudgeScoreConstituents
     */
    'email': PossibleNormJudgeScoreConstituentsEmailEnum;
    /**
     * 
     * @type {number}
     * @memberof PossibleNormJudgeScoreConstituents
     */
    'nameSimilarityScore': number;
    /**
     * 
     * @type {number}
     * @memberof PossibleNormJudgeScoreConstituents
     */
    'otherPotentialNormJudges': number;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormJudgeScoreConstituents
     */
    'phone': PossibleNormJudgeScoreConstituentsPhoneEnum;
}

type PossibleNormJudgeScoreConstituentsAddressEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'
type PossibleNormJudgeScoreConstituentsEmailEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'
type PossibleNormJudgeScoreConstituentsPhoneEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'


