/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PossibleNormJudgeScoreConstituents } from './possible-norm-judge-score-constituents';

/**
 * 
 * @export
 * @interface PossibleNormJudge
 */
export interface PossibleNormJudge {
    /**
     * 
     * @type {string}
     * @memberof PossibleNormJudge
     */
    'associatedNormAttorneysAPI': string;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormJudge
     */
    'associatedNormLawFirmsAPI': string;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormJudge
     */
    'associatedNormPartiesAPI': string;
    /**
     * 
     * @type {boolean}
     * @memberof PossibleNormJudge
     */
    'bestMatch': boolean;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormJudge
     */
    'caseCountAnalyticsByNormJudgeAPI': string;
    /**
     * 
     * @type {number}
     * @memberof PossibleNormJudge
     */
    'confidenceScore': number | null;
    /**
     * Link to Details For the Judge.
     * @type {string}
     * @memberof PossibleNormJudge
     */
    'normJudgeAPI': string;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormJudge
     */
    'normJudgeId': string;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormJudge
     */
    'normJudgeName': string;
    /**
     * Name of the object
     * @type {string}
     * @memberof PossibleNormJudge
     */
    'object': string;
    /**
     * 
     * @type {PossibleNormJudgeScoreConstituents}
     * @memberof PossibleNormJudge
     */
    'scoreConstituents': PossibleNormJudgeScoreConstituents | null;
}

