/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PossibleNormAttorneyScoreConstituents
 */
export interface PossibleNormAttorneyScoreConstituents {
    /**
     * 
     * @type {string}
     * @memberof PossibleNormAttorneyScoreConstituents
     */
    'address': PossibleNormAttorneyScoreConstituentsAddressEnum;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormAttorneyScoreConstituents
     */
    'barId': PossibleNormAttorneyScoreConstituentsBarIdEnum;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormAttorneyScoreConstituents
     */
    'email': PossibleNormAttorneyScoreConstituentsEmailEnum;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormAttorneyScoreConstituents
     */
    'lawFirm': PossibleNormAttorneyScoreConstituentsLawFirmEnum;
    /**
     * 
     * @type {number}
     * @memberof PossibleNormAttorneyScoreConstituents
     */
    'nameSimilarityScore': number;
    /**
     * 
     * @type {number}
     * @memberof PossibleNormAttorneyScoreConstituents
     */
    'otherPotentialNormAttorneys': number;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormAttorneyScoreConstituents
     */
    'phone': PossibleNormAttorneyScoreConstituentsPhoneEnum;
}

type PossibleNormAttorneyScoreConstituentsAddressEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'
type PossibleNormAttorneyScoreConstituentsBarIdEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'
type PossibleNormAttorneyScoreConstituentsEmailEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'
type PossibleNormAttorneyScoreConstituentsLawFirmEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'
type PossibleNormAttorneyScoreConstituentsPhoneEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'


