/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PossibleNormPartyScoreConstituents
 */
export interface PossibleNormPartyScoreConstituents {
    /**
     * 
     * @type {string}
     * @memberof PossibleNormPartyScoreConstituents
     */
    'address': PossibleNormPartyScoreConstituentsAddressEnum;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormPartyScoreConstituents
     */
    'email': PossibleNormPartyScoreConstituentsEmailEnum;
    /**
     * 
     * @type {number}
     * @memberof PossibleNormPartyScoreConstituents
     */
    'nameSimilarityScore': number;
    /**
     * 
     * @type {number}
     * @memberof PossibleNormPartyScoreConstituents
     */
    'otherPotentialNormParties': number;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormPartyScoreConstituents
     */
    'phone': PossibleNormPartyScoreConstituentsPhoneEnum;
    /**
     * 
     * @type {string}
     * @memberof PossibleNormPartyScoreConstituents
     */
    'secretaryOfStateId': PossibleNormPartyScoreConstituentsSecretaryOfStateIdEnum;
}

type PossibleNormPartyScoreConstituentsAddressEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'
type PossibleNormPartyScoreConstituentsEmailEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'
type PossibleNormPartyScoreConstituentsPhoneEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'
type PossibleNormPartyScoreConstituentsSecretaryOfStateIdEnum = 'Matched' | 'Mismatched' | 'Not_Provided_By_Data_Source'


