/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RawOrderedDataChild } from './raw-ordered-data-child';

/**
 * 
 * @export
 * @interface RawOrderedData
 */
export interface RawOrderedData {
    /**
     * Any docket text that belongs to the main docket text is added in the child.
     * @type {Array<RawOrderedDataChild>}
     * @memberof RawOrderedData
     */
    'childArray': Array<RawOrderedDataChild>;
    /**
     * Label of the docket from the source.
     * @type {string}
     * @memberof RawOrderedData
     */
    'lbl': string | null;
    /**
     * Structure order
     * @type {number}
     * @memberof RawOrderedData
     */
    'ord': number;
    /**
     * List of available addresses.
     * @type {string}
     * @memberof RawOrderedData
     */
    'val': string | null;
}

