/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Contact object Data Schema.
 * @export
 * @interface RawOrderedDataChildChildArrayInner
 */
export interface RawOrderedDataChildChildArrayInner {
    /**
     * 
     * @type {Array<object>}
     * @memberof RawOrderedDataChildChildArrayInner
     */
    'childArray': Array<object>;
    /**
     * Label of the docket from the source.
     * @type {string}
     * @memberof RawOrderedDataChildChildArrayInner
     */
    'lbl': string | null;
    /**
     * Structure order.
     * @type {number}
     * @memberof RawOrderedDataChildChildArrayInner
     */
    'ord': number;
    /**
     * List of available addresses.
     * @type {string}
     * @memberof RawOrderedDataChildChildArrayInner
     */
    'val': string | null;
}

