/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Object consisiting of each docket entry number and its corresponding API call.
 * @export
 * @interface ReferencedDocketNumber
 */
export interface ReferencedDocketNumber {
    /**
     * Link to Docket Entries API with the current docket number. The response of this API will give all the primary documents and secondary documents that are associated to it.
     * @type {string}
     * @memberof ReferencedDocketNumber
     */
    'docketEntriesAPI': string | null;
    /**
     * Each referenced docket number
     * @type {number}
     * @memberof ReferencedDocketNumber
     */
    'docketNumber': number;
    /**
     * Name of the object
     * @type {string}
     * @memberof ReferencedDocketNumber
     */
    'object': string;
}

