/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Schedule
 */
export interface Schedule {
    /**
     * [] -> if schedule type is daily <br> 1-7 -> if schedule type is weekly <br> 1-31 -> if schedule type is monthly 
     * @type {Array<number>}
     * @memberof Schedule
     */
    'days': Array<number>;
    /**
     * Name of the object.
     * @type {string}
     * @memberof Schedule
     */
    'object': string;
    /**
     * 
     * @type {string}
     * @memberof Schedule
     */
    'type': ScheduleTypeEnum;
}

type ScheduleTypeEnum = 'daily' | 'weekly' | 'monthly'


