/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A timeline of courts where the judge has been employed.
 * @export
 * @interface ServiceHistory
 */
export interface ServiceHistory {
    /**
     * Title held by the Judge.
     * @type {string}
     * @memberof ServiceHistory
     */
    'title': string | null;
    /**
     * The President-in-charge of the Judges appointment.
     * @type {string}
     * @memberof ServiceHistory
     */
    'appointedBy': string | null;
    /**
     * The year in which the Judge began practicing in his current service.
     * @type {string}
     * @memberof ServiceHistory
     */
    'fromDate': string | null;
    /**
     * The year in which the Judge began practicing in his current service.
     * @type {number}
     * @memberof ServiceHistory
     */
    'fromYear': number | null;
    /**
     * Boolean indicating if the service history  is visible or not.
     * @type {boolean}
     * @memberof ServiceHistory
     */
    'isVisible': boolean;
    /**
     * 
     * @type {string}
     * @memberof ServiceHistory
     */
    'object': string;
    /**
     * The reason for the Judges termination for the current position.
     * @type {string}
     * @memberof ServiceHistory
     */
    'reasonForTermination': string | null;
    /**
     * The court served by the Judge. The court is taken from source.
     * @type {string}
     * @memberof ServiceHistory
     */
    'sourceCourt': string | null;
    /**
     * The year in which the Judge stoped practicing in his current service.
     * @type {string}
     * @memberof ServiceHistory
     */
    'toDate': string | null;
    /**
     * The year in which the Judge stoped practicing in his current service.
     * @type {number}
     * @memberof ServiceHistory
     */
    'toYear': number | null;
}

