/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssociatedSoSPerson } from './associated-so-sperson';
import { Contact } from './contact';
import { SOSAssociatedNormOrganization } from './sosassociated-norm-organization';
import { SOSNameChange } from './sosname-change';

/**
 * 
 * @export
 * @interface SOSData
 */
export interface SOSData {
    /**
     * 
     * @type {Array<AssociatedSoSPerson>}
     * @memberof SOSData
     */
    'associatedSoSPersonArray': Array<AssociatedSoSPerson>;
    /**
     * 
     * @type {Contact}
     * @memberof SOSData
     */
    'contact': Contact;
    /**
     * 
     * @type {boolean}
     * @memberof SOSData
     */
    'domesticRegistration': boolean;
    /**
     * 
     * @type {string}
     * @memberof SOSData
     */
    'fein': string | null;
    /**
     * 
     * @type {string}
     * @memberof SOSData
     */
    'firstFetchDate': string;
    /**
     * 
     * @type {string}
     * @memberof SOSData
     */
    'inactivationDate': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SOSData
     */
    'isActive': boolean;
    /**
     * 
     * @type {string}
     * @memberof SOSData
     */
    'lastFetchDate': string;
    /**
     * Last Fetch Date of Organization with Updates.
     * @type {string}
     * @memberof SOSData
     */
    'lastFetchDateWithUpdates': string;
    /**
     * 
     * @type {Array<SOSNameChange>}
     * @memberof SOSData
     */
    'nameChangesArray': Array<SOSNameChange>;
    /**
     * 
     * @type {string}
     * @memberof SOSData
     */
    'object': string;
    /**
     * 
     * @type {string}
     * @memberof SOSData
     */
    'registeredDate': string | null;
    /**
     * 
     * @type {Array<SOSAssociatedNormOrganization>}
     * @memberof SOSData
     */
    'sosAssociatedNormOrganizationArray': Array<SOSAssociatedNormOrganization>;
    /**
     * 
     * @type {string}
     * @memberof SOSData
     */
    'sosNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof SOSData
     */
    'stateCode': string;
    /**
     * 
     * @type {string}
     * @memberof SOSData
     */
    'status': SOSDataStatusEnum;
}

type SOSDataStatusEnum = 'Active'


