/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NatureOfSuit } from './nature-of-suit';
import { SourceCauseOfAction } from './source-cause-of-action';
import { SourceCharge } from './source-charge';
import { SourcePageData } from './source-page-data';

/**
 * Source data in the court website.
 * @export
 * @interface SourceCaseData
 */
export interface SourceCaseData {
    /**
     * Array of Charges for a case which is provided by the Court.
     * @type {Array<NatureOfSuit>}
     * @memberof SourceCaseData
     */
    'natureOfSuitArray': Array<NatureOfSuit>;
    /**
     * Name of the object
     * @type {string}
     * @memberof SourceCaseData
     */
    'object': string;
    /**
     * Case Status as provided by Court.
     * @type {string}
     * @memberof SourceCaseData
     */
    'sourceCaseStatus': string;
    /**
     * Case Type for a case which is provided by the Court.
     * @type {string}
     * @memberof SourceCaseData
     */
    'sourceCaseType': string;
    /**
     * Array of Cause Of Action for a case which is provided by the Court.
     * @type {Array<SourceCauseOfAction>}
     * @memberof SourceCaseData
     */
    'sourceCauseOfActionArray': Array<SourceCauseOfAction>;
    /**
     * Array of Charges for a case which is provided by the Court.
     * @type {Array<SourceCharge>}
     * @memberof SourceCaseData
     */
    'sourceChargeArray': Array<SourceCharge>;
    /**
     * Courtrhouse as provided by Court.
     * @type {string}
     * @memberof SourceCaseData
     */
    'sourceCourt': string;
    /**
     * 
     * @type {Array<SourcePageData>}
     * @memberof SourceCaseData
     */
    'sourcePageData': Array<SourcePageData>;
}

