/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Source Cause of Action data from the source site.
 * @export
 * @interface SourceCauseOfAction
 */
export interface SourceCauseOfAction {
    /**
     * When this Cause of Action was first fetched from the court site.
     * @type {string}
     * @memberof SourceCauseOfAction
     */
    'firstFetchDate': string;
    /**
     * Signifies if the cause of action is currently isVisible or not for the case.
     * @type {boolean}
     * @memberof SourceCauseOfAction
     */
    'isVisible': boolean;
    /**
     * When this Cause of Action was last fetched from the court site.
     * @type {string}
     * @memberof SourceCauseOfAction
     */
    'lastFetchDate': string;
    /**
     * Name of the object
     * @type {string}
     * @memberof SourceCauseOfAction
     */
    'object': string;
    /**
     * Cause of Action data from the source site.
     * @type {string}
     * @memberof SourceCauseOfAction
     */
    'sourceCauseOfAction': string | null;
    /**
     * Raw Cause of Action data from the source site.
     * @type {string}
     * @memberof SourceCauseOfAction
     */
    'sourceCauseOfActionRaw': string | null;
    /**
     * Statute of a Cause of Action.
     * @type {string}
     * @memberof SourceCauseOfAction
     */
    'sourceStatute': string | null;
}

