/*
UniCourt Enterprise APIs

<button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button>


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExtractedFields } from './extracted-fields';
import { RawOrderedData } from './raw-ordered-data';

/**
 * 
 * @export
 * @interface SourceStructuredData
 */
export interface SourceStructuredData {
    /**
     * 
     * @type {ExtractedFields}
     * @memberof SourceStructuredData
     */
    'extractedFields': ExtractedFields | null;
    /**
     * 
     * @type {Array<RawOrderedData>}
     * @memberof SourceStructuredData
     */
    'rawOrderedDataArray': Array<RawOrderedData>;
}

